### ISSUE TITLE
Input Shape Error

### ISSUE THREAD

**Issue by larissapalethorpe** [aidenrolfe/ARG#18]
Tried to run 1000 galaxies through the network and received `ValueError: Input 1 is incompatible with layer model_14: expected shape=(None, 2), found shape=(None, 1000, 2)`. Did some playing around and realised this only happens when conditional=True. I'm unsure where this error has come from because it wasn't happening before and the only thing that I've changed is the import code at the beginning, since the galaxies.py file changed and I had to make it compatible. I realise this is an array size problem but really can't figure out where exactly the input issue is to change it since I don't think I'm giving an input_shape with 3 arguments anywhere - I'd be grateful for any advice or clarification, what exactly is layer model_14?

**Comment by bamford** [comment]
If this is using Aiden’s code before my recent changes, then the redshifts array has an extra dimension. You can do np.squeeze as soon as you’ve read it. This will get rid of the extra dimension, but still work with the updated version.

**Comment by larissapalethorpe** [comment]
I believe that it is the version with your recent changes, I was just using the most up to date version on main which is 15 hours old. I tried adding in np.squeeze for both z_input and z_target just after reading them in but I'm still getting the same version.

**Comment by bamford** [comment]
So, the issue with the shape error is just that you have code left over from when z_input and z_target were the wrong shape. You just need to delete [lines 22 & 23](https://github.com/aidenrolfe/ARG/blob/f0651a355fbe8d62a14337c2a136a552271e5d27/GalaxiesVAE.py#L22).

Once that was done, the code ran, but I found that the loss was giving NaNs (or at least very large numbers). This is presumably because of the very different normalisation of the galaxy images compared to MNIST digits. The latter are all 0-1, but the galaxies (1) have a different overall normalisation (although not far of a standard deviation of 1), and more importantly (2) all over the place, depending on redshift.

As we can't assume the output is 0-1, we must remove the "sigmoid" activation in [the final layer](https://github.com/aidenrolfe/ARG/blob/f0651a355fbe8d62a14337c2a136a552271e5d27/GalaxiesVAE.py#L93). I only noticed that after messing about for a while. I'm not sure if that in itself is enough network to get the network to train.

The other thing I did was to normalise the galaxies individually. A first it may seem that this removes useful information. However, (1) I think this info is only necessary to interpret/reproduce the noise correctly (and we aren't using noisy images yet), and (2) we could add the normalisation values in to the network as a condition (alongside the redshifts). The other problem with this is that at "inference time" we wouldn't have the normalisation of the output images (unlike during training/testing). A solution to that might be to get the network to output the normalisation along with the image.

To make sure I could get the network to train with an easier problem, I changed the targets to the inputs in `.fit` (i.e. just trying to get the model to learn the inputs, not the transformation to the target). I also turned off the condition. I created 2500 galaxies with `galaxies.py`, with random redshifts. (Fixed redshifts would be easier, so maybe I should have started there.)

With that done, the network [seems to train ok](https://github.com/aidenrolfe/ARG/files/6218117/examples.pdf) (but remember only training to reproduce the inputs so far).

While messing about, I also changed the architecture of the network a little bit. However, I doubt it makes a lot of difference.

My latest code is pushed to the devSteven_CVAE branch. However, I suggest you don't merge, but [compare the changes](https://github.com/aidenrolfe/ARG/pull/20/files) and make the more important ones to your code in turn, to see the effect.

p.s. it would be wise to separate out the code that creates the reconstructions and make the plots, so you can make more plots (e.g. a variety of example galaxies) without having to train the model each time.

**Comment by larissapalethorpe** [comment]
Great thank you, I'm still playing around with things right now but am happy to meet tomorrow to show you some of my reconstructions. I was also just curious as to why you'd used 32 latent dimensions on your branch?

**Comment by bamford** [comment]
Before I discovered the sigmoid issue, I tried changing a few things to see if it made a difference. It will have some effect (something you could examine), but I’d guess that a smaller number would still work (but not too small, as we discussed). Remember that you should make sure the layer before is not smaller than the latent layer itself.

**Comment by larissapalethorpe** [comment]
I left the code with a training set of 10,000 images, beta 0.1, 20 latent dimensions, for a maximum of 1000 epochs all day and all night and it was done this morning after training for 400 epochs with `loss: 9.4115 - reconstruction_loss: 5.9950 - kl_loss: 3.4227 - val_loss: 9.8944 - val_reconstruction_loss: 6.4833 - val_kl_loss: 3.4091`. The reconstructions are also great
![Figure_59a](https://user-images.githubusercontent.com/78367556/113136932-d594c080-921b-11eb-8839-a1f55a95efff.png), and there are more in my lab book. I'll continue to experiment with it over easter, I just had 2 final questions. I've not experimented with changing beta so far, is that likely to have any effect? I was also wondering what exactly changing the strides did?

**Comment by bamford** [comment]
Yay! This is excellent.

Note that the redshifts in the titles of these plots are all the same, so presumably wrong. (I noticed that before and thought I'd fixed it.)

The only thing I'd do to beta for now would be consider putting it back to its "normal" value of 1, as long as it doesn't hurt the reconstruction loss. Ideally at some point one would do a 'hyper-parameter optimisation", exploring a variety of values for as many relevant hyper-parameters as possible (such as beta, kernel size, latent dimension, optimizer, ...). However, I think that is probably beyond the scope of this project.

The strides are part of the whole architecture. You can't change them without changing something else. A stride == 1 means that the convolution kernel is applied at the position of every pixel in the preceding layer, so the result has the same size (modulo edge padding effects). A stride == 2 means that the kernel is applied at every other pixel, which produces a result of half the size (again assuming `padding="same"`).
![](https://miro.medium.com/max/588/1*BMngs93_rm2_BpJFH2mS0Q.gif)

If you change the stride, then the sizes of the layers will vary. You would then need to consider changing the number of layers, so you still have a reasonable number of parameters going into your latent layer (for the encoder), and you produce the correct size output (for the decoder). By the way, [this paper](https://arxiv.org/abs/1707.02937) advises that strides should be a multiple of the kernel size in transpose convolutions (the decoder) to avoid artefacts.

I suggest you focus on:
1. making nice figures to demonstrate what the network is doing
2. trying different combinations of input and target, as discussed in the meeting:
  * input "standard", target "standard" (what you're doing now)
  * input "observed, noisy", target "observed, noisy" (full artificial redshifting)
3. seeing what happens when switch things round to go from high-z inputs to low-z targets
  * input "observed, noisy", target "observed, noisy" (de-redshifting)
  * input "observed, noisy", target "observed, no noisy" (de-redshifting and noise removal)
  * input "observed, noisy", target "standard" (de-redshifting, noise removal and deconvolution)
4. training with more complex 'galaxies', e.g. by simply adding together combinations of sersics (before SEDs are applied)

If you _really_ run out of things to try, then it would be great to build in uncertainties on the output images. See [this paper](https://ui.adsabs.harvard.edu/abs/2017ApJ...850L...7P/abstract), which has been used by some people in the Nottingham astro group [here](https://ui.adsabs.harvard.edu/abs/2021arXiv210303257P/abstract).
