### ISSUE TITLE
Plotting digit classes in latent space

### ISSUE THREAD

**Issue by larissapalethorpe** [aidenrolfe/ARG#9]
I'm having trouble with the 2D plots of the digit classes in latent space. I'm currently using
`x_test_encoded = encoder.predict([x_test_noisy, y_test], batch_size=batch_size)
plt.scatter(x_test_encoded[0], x_test_encoded[1], c=y_test)
plt.colorbar()
plt.show()`
However, this isn't working because the array sizes of x_test_encoded don't match up with y_test. I still don't entirely understand what y_test is, so haven't been able to rectify it.

**Comment by bamford** [comment]
Providing the exact code and error messages make figuring out this kind of thing much easier.

Printing out the shape and some examples from `y_test` at different stages in the code should make it clear what `y_test` is. This is fairly standard problem solving...

I suspect that the problem you are having is that it the call to `predict` needs the `y_test` input to be "one-hot encoded" (an array of probabilities for each class, assuming you haven't changed it), which is achieved by [`to_categorical`](https://github.com/aidenrolfe/ARG/blob/1f62ac8de79d8013a36ccd2e41a7ca2b2a419544/VAE.py#L41). However, `scatter` is expecting its `c` argument to be an array of numbers, which it maps on to the colormap (i.e. `y_test` before `to_categorical`).

**Comment by larissapalethorpe** [comment]
Ah ok I think I see what you're saying although I'm still getting errors as the array sizes don't match: `ValueError: 'c' argument has 10000 elements, which is inconsistent with 'x' and 'y' with size 20000.` However, looking at examples I think y_train might be better than y_test in this case, although that has 60000 elements, can I just extract the first 20000 elements from this or is that not advisable? I did attempt this for y_test but then I got the error `ValueError: 'c' argument has 2000 elements, which is inconsistent with 'x' and 'y' with size 20000.`  I've edited the VAE.py code on my branch to give a better view of what I'm trying to do (whilst also adding in a callback so that it stops training if there is no improvement to the validation after 3 epochs).

**Comment by bamford** [comment]
The output of the encoder is a list with three elements: `z_mean`, `z_logvar` and `z`, see [this line](https://github.com/aidenrolfe/ARG/blob/98e961e29271485357be6a3d78f95b3165c675df/VAE.py#L81). Each of these is shape (10000, 2), as you have 10000 examples and a latent dimension of 2. To get the first latent dimension you therefore need `z[:, 0]`.

**Comment by bamford** [comment]
Just following up on something you said...

If you have written code to do something and you get an error, in this case that the sizes of the arrays don't match, that is telling you there is something wrong, either with your implementation of the code, or the approach itself. You should work out what is wrong, why it is wrong, and how to fix the code such that it does what you intend. You should not just do the first, or simplest, thing that might get rid of the specific error; in doing so you may avoid the error, but your resulting code will likely be doing the wrong thing. There are many more ways to write code that is meaningless (but "error-free"), than there are versions that correctly do something useful.

Here the array size error is telling you that the outputs of the encoder don't match what you have assumed in the plotting code. Probably because you have copied the code from elsewhere, rather than _writing_ code to do the specific thing you are trying to do.

`x_test` is a set of images of digits. `y_test` tells you which digit is in the image (0, 1, 2, 3, ...).
`x_train` is a different set of images, containing the digits given in `y_train`.
Hopefully it is obvious that you need `y` to match what is actually in `x`, otherwise it isn't supplying any useful information. You therefore can't just go and take random `y` values from somewhere else!

**Comment by larissapalethorpe** [comment]
Just wanted to say that from what you said at the last meeting I understand copying and pasting is not a good approach. I had attempted to write my own version of the function they'd used in the original Keras example to plot the digit classes, but since our code is now quite different to that one I was slightly confused to the differences caused by our version having 2 input tensors. I thought just extracting some numbers from the y_test likely wasn't the way to go, and tried to go back and understand what I was doing wrong but it wasn't abundantly clear to me, but thank you for correcting it I think I have better understanding now!
